name: Create Release
on:
  push:
    tags:
      - "v*.*.*"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: softprops/action-gh-release@v1
        with:
          body: |
            [Changelog](https://github.com/Glavo/classfile/blob/main/CHANGELOG.md)
