name: Create Release
on:
  push:
    tags:
      - "*.*.*"
jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: softprops/action-gh-release@v1
        with:
          body: |
            [Changelog](https://github.com/Glavo/classfile/blob/main/CHANGELOG.md)
